/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Usuario
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JB_Comprar = new javax.swing.JButton();
        JB_Administrar = new javax.swing.JButton();
        JDK_escritorioPrincipal = new javax.swing.JDesktopPane();
        JB_Duitama = new javax.swing.JButton();
        JB_Sogamoso = new javax.swing.JButton();
        JB_Tunja = new javax.swing.JButton();
        JB_Paipa = new javax.swing.JButton();
        JB_Terminales = new javax.swing.JToggleButton();
        JB_Buses = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JB_Comprar.setText("Comprar");

        JB_Administrar.setText("Administrar");
        JB_Administrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_AdministrarActionPerformed(evt);
            }
        });

        JB_Duitama.setText("DUITAMA");
        JB_Duitama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_DuitamaActionPerformed(evt);
            }
        });

        JB_Sogamoso.setText("SOGAMOSO");

        JB_Tunja.setText("TUNJA");

        JB_Paipa.setText("PAIPA");

        JB_Terminales.setText("TERMINALES");

        JB_Buses.setText("BUSES");

        JDK_escritorioPrincipal.setLayer(JB_Duitama, javax.swing.JLayeredPane.DEFAULT_LAYER);
        JDK_escritorioPrincipal.setLayer(JB_Sogamoso, javax.swing.JLayeredPane.DEFAULT_LAYER);
        JDK_escritorioPrincipal.setLayer(JB_Tunja, javax.swing.JLayeredPane.DEFAULT_LAYER);
        JDK_escritorioPrincipal.setLayer(JB_Paipa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        JDK_escritorioPrincipal.setLayer(JB_Terminales, javax.swing.JLayeredPane.DEFAULT_LAYER);
        JDK_escritorioPrincipal.setLayer(JB_Buses, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout JDK_escritorioPrincipalLayout = new javax.swing.GroupLayout(JDK_escritorioPrincipal);
        JDK_escritorioPrincipal.setLayout(JDK_escritorioPrincipalLayout);
        JDK_escritorioPrincipalLayout.setHorizontalGroup(
            JDK_escritorioPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDK_escritorioPrincipalLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addGroup(JDK_escritorioPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JDK_escritorioPrincipalLayout.createSequentialGroup()
                        .addComponent(JB_Tunja)
                        .addGap(58, 58, 58)
                        .addComponent(JB_Paipa))
                    .addComponent(JB_Terminales))
                .addGap(44, 44, 44)
                .addGroup(JDK_escritorioPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JDK_escritorioPrincipalLayout.createSequentialGroup()
                        .addComponent(JB_Duitama)
                        .addGap(49, 49, 49)
                        .addComponent(JB_Sogamoso))
                    .addComponent(JB_Buses, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(377, Short.MAX_VALUE))
        );
        JDK_escritorioPrincipalLayout.setVerticalGroup(
            JDK_escritorioPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDK_escritorioPrincipalLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(JDK_escritorioPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_Terminales)
                    .addComponent(JB_Buses))
                .addGap(55, 55, 55)
                .addGroup(JDK_escritorioPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_Tunja)
                    .addComponent(JB_Paipa)
                    .addComponent(JB_Duitama)
                    .addComponent(JB_Sogamoso))
                .addContainerGap(382, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(JB_Administrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JB_Comprar)
                .addGap(195, 195, 195))
            .addComponent(JDK_escritorioPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_Administrar)
                    .addComponent(JB_Comprar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JDK_escritorioPrincipal))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_AdministrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_AdministrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JB_AdministrarActionPerformed

    private void JB_DuitamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_DuitamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JB_DuitamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JB_Administrar;
    public javax.swing.JToggleButton JB_Buses;
    public javax.swing.JButton JB_Comprar;
    public javax.swing.JButton JB_Duitama;
    public javax.swing.JButton JB_Paipa;
    public javax.swing.JButton JB_Sogamoso;
    public javax.swing.JToggleButton JB_Terminales;
    public javax.swing.JButton JB_Tunja;
    public javax.swing.JDesktopPane JDK_escritorioPrincipal;
    // End of variables declaration//GEN-END:variables
}
